package com.cooksys.frontend.model;

// Generated Jun 9, 2015 3:55:11 PM by Hibernate Tools 4.3.1

/**
 * PlaneFlight generated by hbm2java
 */
public class PlaneFlight implements java.io.Serializable {

	private Integer id;
	private int tripId;
	private Boolean cancelled;
	private String originCity;
	private String originState;
	private Integer departure;
	private Integer eta;
	private int flightId;
	private String destinationCity;
	private String destinationState;
	private Boolean late;
	private boolean arrived;

	public PlaneFlight() {
	}

	public PlaneFlight(int tripId, int flightId, String destinationCity,
			boolean arrived) {
		this.tripId = tripId;
		this.flightId = flightId;
		this.destinationCity = destinationCity;
		this.arrived = arrived;
	}

	public PlaneFlight(int tripId, Boolean cancelled, String originCity,
			String originState, Integer departure, Integer eta, int flightId,
			String destinationCity, String destinationState, Boolean late,
			boolean arrived) {
		this.tripId = tripId;
		this.cancelled = cancelled;
		this.originCity = originCity;
		this.originState = originState;
		this.departure = departure;
		this.eta = eta;
		this.flightId = flightId;
		this.destinationCity = destinationCity;
		this.destinationState = destinationState;
		this.late = late;
		this.arrived = arrived;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getTripId() {
		return this.tripId;
	}

	public void setTripId(int tripId) {
		this.tripId = tripId;
	}

	public Boolean getCancelled() {
		return this.cancelled;
	}

	public void setCancelled(Boolean cancelled) {
		this.cancelled = cancelled;
	}

	public String getOriginCity() {
		return this.originCity;
	}

	public void setOriginCity(String originCity) {
		this.originCity = originCity;
	}

	public String getOriginState() {
		return this.originState;
	}

	public void setOriginState(String originState) {
		this.originState = originState;
	}

	public Integer getDeparture() {
		return this.departure;
	}

	public void setDeparture(Integer departure) {
		this.departure = departure;
	}

	public Integer getEta() {
		return this.eta;
	}

	public void setEta(Integer eta) {
		this.eta = eta;
	}

	public int getFlightId() {
		return this.flightId;
	}

	public void setFlightId(int flightId) {
		this.flightId = flightId;
	}

	public String getDestinationCity() {
		return this.destinationCity;
	}

	public void setDestinationCity(String destinationCity) {
		this.destinationCity = destinationCity;
	}

	public String getDestinationState() {
		return this.destinationState;
	}

	public void setDestinationState(String destinationState) {
		this.destinationState = destinationState;
	}

	public Boolean getLate() {
		return this.late;
	}

	public void setLate(Boolean late) {
		this.late = late;
	}

	public boolean isArrived() {
		return this.arrived;
	}

	public void setArrived(boolean arrived) {
		this.arrived = arrived;
	}

}
