package com.cooksys.frontend.model;

// Generated Jun 8, 2015 9:41:37 AM by Hibernate Tools 4.3.1

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

	private Integer id;
	private int tripId;
	private int flightId;

	public Ticket() {
	}

	public Ticket(int tripId, int flightId) {
		this.tripId = tripId;
		this.flightId = flightId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getTripId() {
		return this.tripId;
	}

	public void setTripId(int tripId) {
		this.tripId = tripId;
	}

	public int getFlightId() {
		return this.flightId;
	}

	public void setFlightId(int flightId) {
		this.flightId = flightId;
	}

}
